### ISSUE TITLE
Failed to require the main module of 'jump-to-import'

### ISSUE THREAD

**Issue by alexisab** [alexheyd/atom-jump-to-import#23]
When you install the new version of your package, we get a warning in the console : 
```
Failed to require the main module of 'jump-to-import' because it requires one or more incompatible native modules (build).
Run `apm rebuild` in the package directory and restart Atom to resolve.
```

I tried to `apm rebuild` in the folder of jump-to-package without any effect.

**Comment by alexheyd** [comment]
Could you try rebuilding from Atom's "Incompatible Packages" view? There have been previous reports of `apm rebuild` failing from the command line but working from the "Incompatible Packages" view.

Otherwise, you could also try `rm -rf ~/.atom/packages/jump-to-import/node_modules` and rebuilding then.

**Comment by alexisab** [comment]
Yes I did it and now it works.
